spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_aranceles}?sslmode=require
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

ms-matricula:
  url: http://localhost:8083

logging:
  level:
    com.proyecto.ms_aranceles: DEBUG