spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_practicas}?sslmode=require
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

ms-aranceles:
  url: http://localhost:8081
ms-notas:
  url: http://localhost:8086
ms-empresas:
  url: http://localhost:8089

logging:
  level:
    com.proyecto.ms_practicas: DEBUG