spring.application.name=ms-matriculas
server.port=8081


spring.datasource.url=jdbc:postgresql://3sacu4zw.us-east.database.insforge.app:5432/insforge?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=81809dcb1ba3560defb5ce98abd6ba64
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opciones adicionales de configuración de HikariCP (opcional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=HikariCP

# Habilitar logging SQL (opcional, para debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true