spring.application.name=ms-matricula
server.port=8085

# URL corregida con el Host correcto
spring.datasource.url=jdbc:postgresql://cirxv9cp.us-east.database.insforge.app:5432/insforge?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=81809dcb1ba3560defb5ce98abd6ba64
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate detecta el dialecto solo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracion de HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=HikariCP

# Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false