spring:
  application:
    name: ms-carreras
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    table: flyway_schema_history_carreras
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    repair-on-migrate: true

server:
  port: ${PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO